CREATE TABLE IF NOT EXISTS paper_asset (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    paper_id BIGINT NOT NULL,
    asset_type VARCHAR(50) NOT NULL,
    asset_label VARCHAR(255),
    caption LONGTEXT,
    page_start INT NOT NULL,
    page_end INT NOT NULL,
    bounding_box_json TEXT,
    raw_asset_path VARCHAR(1000) NOT NULL,
    raw_text LONGTEXT,
    structured_content_json LONGTEXT,
    extraction_method VARCHAR(50) NOT NULL,
    extraction_confidence DOUBLE NOT NULL DEFAULT 1.0,
    verification_status VARCHAR(50) NOT NULL DEFAULT 'EXTRACTED',
    content_hash VARCHAR(64) NOT NULL,
    parser_version VARCHAR(100) NOT NULL,
    source_revision VARCHAR(64) NOT NULL,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_paper_asset_revision (paper_id, page_start, asset_type, content_hash, parser_version),
    INDEX idx_paper_asset_paper (paper_id),
    INDEX idx_paper_asset_type (paper_id, asset_type),
    CONSTRAINT fk_paper_asset_paper FOREIGN KEY (paper_id) REFERENCES paper_reference(id) ON DELETE CASCADE
) COMMENT='论文页面与基础多模态资产';
