CREATE TABLE IF NOT EXISTS paper_reproduction_fact (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    paper_id BIGINT NOT NULL,
    fact_type VARCHAR(80) NOT NULL,
    fact_key VARCHAR(500) NOT NULL,
    fact_value LONGTEXT NOT NULL,
    unit VARCHAR(100),
    conditions_json LONGTEXT,
    source_kind VARCHAR(50) NOT NULL,
    source_id BIGINT NOT NULL,
    page_number INT,
    evidence_excerpt LONGTEXT NOT NULL,
    confidence DECIMAL(6,5) NOT NULL,
    verification_status VARCHAR(50) NOT NULL,
    conflict_group VARCHAR(100),
    supporting_sources_json LONGTEXT,
    extractor_version VARCHAR(100) NOT NULL,
    source_revision VARCHAR(100),
    qdrant_point_id VARCHAR(100),
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_reproduction_fact_paper (paper_id, verification_status),
    INDEX idx_reproduction_fact_source (source_kind, source_id),
    INDEX idx_reproduction_fact_conflict (paper_id, conflict_group),
    CONSTRAINT fk_reproduction_fact_paper FOREIGN KEY (paper_id) REFERENCES paper_reference(id) ON DELETE CASCADE
) COMMENT='可追溯的论文复现原子事实';
